pepabo/active_merchant-epsilon

README.md
@takatoshiono @tsuchikazu @kenchan @kurotaky
コンビニ決済のサンプルコードにタイポがあって、
そのままコピーして実行すると
```
ArgumentError: missing keyword: phone_number
```
となるので修正しました。
=> コンビニ決済のサンプルコードにタイポがあったので修正する

README.md
There is no url of service url on README. I added it :octocat:
=> added url of epsilon official site

lib/active_merchant/billing/convenience_store.rb
@kurotaky @inouetakuya 
`lib/active_merchant/billing/convenience_store.rb` 内の `valid_code?` メソッドで
コンビニのコードを表す定数にモジュール名がついていなかったため、
`NameError`になっていたので、モジュール名をつけます。
=> モジュール名CodeをつけないとNameErrorになるのでvalid_code?の中の定数にモジュール名をつける

lib/active_merchant/billing/convenience_store.rb
In some projects, the chains of convenience stores other than the ones already added in the module  may be needed.
So, I would like to add other sotre chains code in ActiveMerchant::Billing::ConvenienceStore::Code.
=> add other convenience store codes

.travis.yml
https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/
=> Test Ruby 2.3.0 in Travis

lib/active_merchant/billing/gateways/response_parser.rb
ref: https://github.com/pepabo/active_merchant-epsilon/pull/80#issuecomment-205142757
This convenience payment response doesn't parsed correctly.
I remove one code `@xml.xpath` to correct this problem.
=> Fix response parser method

active_merchant-epsilon.gemspec, lib/active_merchant/billing/gateways/epsilon/epsilon_base.rb, test/test_helper.rb, test/unit/gateways/epsilon_test.rb
According to the Epsilon specification, the request parameters must be encode in `EUC-JP` or `Shift_JIS`. For the specification, this pull request add `encoding` setting.
Usage:
```
ActiveMerchant::Billing::EpsilonBaseGateway.encoding = Encoding::EUC_JP
```
The default encoding value is nil, nothing is encoded.
=> Add encoding setting

lib/active_merchant/billing/gateways/epsilon.rb, lib/active_merchant/billing/gateways/epslion_convenience_store.rb
https://github.com/pepabo/active_merchant-epsilon/pull/83 にて追加したmemoは
値がセットされている時のみイプシロンに送信する。
=> memoは設定されているときのみ値を送信する

lib/active_merchant/billing/gateways/epsilon.rb, lib/active_merchant/epsilon/version.rb
According to the specification, following parameters are accepted even if the payment is registered purchase.
- `card_st_code`
- `pay_time`
=> Send pay time params on registered purchase

lib/active_merchant/billing/gateways/epsilon/epsilon_base.rb, lib/active_merchant/billing/gateways/response_parser.rb
There's `card_expire` parameter in get_user_info.cgi response. Literally it represents registered card expiration in YYYYMM format.
=> card_expire parameter is returned on find_user

CHANGELOG.md, lib/active_merchant/epsilon/version.rb
version0.8.0にあげます。
ref:
https://github.com/pepabo/active_merchant-epsilon/pull/93
=> bump up version0.8.0.

lib/active_merchant/billing/gateways/epsilon.rb, lib/active_merchant/billing/gateways/response_parser.rb, test/fixtures/vcr_cassettes/find_order_failure.yml, test/fixtures/vcr_cassettes/find_order_success.yml, test/remote/gateways/remote_epsilon_test.rb
イプシロンにて決済したオーダーの情報を取得するAPIに対応させます。
ref: `CGI設定マニュアル 他通貨決済対応版 ver.3.0.20` p.71~73
=> オーダー情報確認に対応させる

lib/active_merchant/billing/gateways/epsilon.rb, lib/active_merchant/billing/gateways/response_parser.rb
close: #96 
決済方法がバーチャル口座決済のオーダーは、口座情報の他に入金額も返すようになっているのでこれを取得できるようにします。
ref: `CGI設定マニュアル 他通貨決済対応版 ver.3.0.20` p.71~73
=> オーダー情報確認で入金額を取得できるようにする

active_merchant-epsilon.gemspec
There is no code that depends on a particular version. So, we use the latest version.
=> Update dependencies version

lib/active_merchant/billing/gateways/response_parser.rb
`URI.decode` is obsolete method. In this case, it is appropriate to use `CGI.unescape`.
https://docs.ruby-lang.org/en/latest/class/URI.html#S_DECODE
=> Fix use of the obsolete method

lib/active_merchant/billing/gateways/epsilon_gmo_after.rb, lib/active_merchant/billing/gateways/response_parser.rb, test/fixtures/vcr_cassettes/gmo_after_purchase_fail.yml, test/fixtures/vcr_cassettes/gmo_after_purchase_successful.yml, test/remote/gateways/remote_epsilon_convenience_store_test.rb, test/remote/gateways/remote_epsilon_gmo_after_test.rb, test/remote/gateways/remote_epsilon_gmo_id_test.rb, test/remote/gateways/remote_epsilon_test.rb, test/remote/gateways/remote_epsilon_virtual_account_test.rb, test/test_helper.rb
- 他決済に揃えるため、GMO後払いでも version 1 を使うようにしました
- レスポンスの文字コード変換が適切に行われているかのテストを追加しました
参考：`イプシロン決済システム仕様書 Ver.1.0.41 p44, 45`
=> GMO後払い version 1 を使うようにする

lib/active_merchant/billing/gateways/epsilon.rb, lib/active_merchant/billing/gateways/epsilon/epsilon_base.rb, lib/active_merchant/billing/gateways/response_parser.rb, test/fixtures/vcr_cassettes/capture_failure.yml, test/fixtures/vcr_cassettes/capture_success.yml, test/fixtures/vcr_cassettes/capture_success_authorize.yml, test/fixtures/vcr_cassettes/purchase_with_capture_false_successful.yml, test/fixtures/vcr_cassettes/purchase_with_capture_true_successful.yml, test/remote/gateways/remote_epsilon_test.rb
- Makes purchase methods accept `capture` flag.
- This will be sent as `kari_flag` to specify capture or not.
- If not given, the setting configured in epsilon dashboard is used.
- Implements `capture` method which captures authorized payments.
=> Capture authorized payments

CHANGELOG.md, lib/active_merchant/epsilon/version.rb
https://github.com/pepabo/active_merchant-epsilon/pull/114 でイプシロンリンクタイプ決済の取消しを行う `void` メソッドを追加しました。
=> Bump up version 0.11.0

CHANGELOG.md, lib/active_merchant/epsilon/version.rb
イプシロンリンクタイプで決済を行う `purchase` メソッド利用時に、配送情報を送信するかどうかを引数に渡して選択できるようにしました。 https://github.com/pepabo/active_merchant-epsilon/pull/116 
後方互換性のある機能追加のため、マイナーバージョンを上げます。
=> Bump up version 0.12.0

lib/active_merchant/billing/gateways/epsilon.rb, lib/active_merchant/billing/gateways/response_parser.rb, test/remote/gateways/remote_epsilon_test.rb
オーダー情報確認CGIのレスポンスには注文日時（last_update）が含まれています。
注文日時にアクセスできた方が調査などの場面で便利であるため、レスポンスのパラメーターに注文日時（last_update）を追加しました。
=> オーダー情報確認CGIのレスポンスに注文日時を追加

.github/workflows/test.yml
- 「fork運用でPRを作成した際、CIの実行がApproveされても実行されない」という現象に対するPRです
- CI をトリガーするタイミングに on: pull_request を追加し、push に branches master 条件を追加
- fork運用でPRを出した際にもCIがトリガーされる & 二重で CI がトリガーされないようにしています
- https://github.com/pepabo/active_merchant-epsilon/pull/122
- https://github.com/pepabo/active_merchant-epsilon/pull/123
=> CIをトリガーする条件に pull_request を追加

README.md, lib/active_merchant/billing/gateways/epsilon.rb, lib/active_merchant/billing/gateways/epsilon/epsilon_base.rb, lib/active_merchant/billing/gateways/response_parser.rb, test/fixtures/vcr_cassettes/authenticate_with_three_d_secure_2_successful.yml, test/fixtures/vcr_cassettes/purchase_with_three_d_secure_2_successful.yml, test/remote/gateways/remote_epsilon_test.rb, test/test_helper.rb
3Dセキュア1.0は2022年10月13日に閉塞されるので、3Dセキュア2.0に対応できるようにします。
変更内容詳細や仕様書は[イプシロンからのお知らせ](https://www.epsilon.jp/news/20220726.html)にあります。
対応内容は以下です。
* 通常決済と登録済み課金の場合に3Dセキュア2.0に必要なパラメータを渡せるようにした
* `purchase` と `registered_purchase` に対応
* 月次課金（ `registered_recurring` ）は3Dセキュア対応のクレジットカードが利用できないので対応していない
* APIの改修が終わったので `registered_purchase` のテストも登録済み課金 + 3Dセキュア2.0用のVCRカセットを使用 ~`registered_purchase` のテストは一時的に他のVCRカセットを使って追加~ 
* イプシロンのAPIに不具合があり、APIを叩いても正常なレスポンスが返ってこないので
* 不具合が改修された後にVCRカセットを取り直す予定 => APIの改修が終わったのでVCRカセットを取り直した
* READMEに3Dセキュア2.0の場合を追加
=> クレジットカード決済を3Dセキュア2.0に対応する

CHANGELOG.md, lib/active_merchant/epsilon/version.rb
クレジットカード決済を3Dセキュア2.0に対応したのでバージョンを `0.14.0` に上げます。
https://github.com/pepabo/active_merchant-epsilon/pull/121
=> Bump up version 0.14.0

.github/workflows/test.yml, test/remote/gateways/remote_epsilon_convenience_store_test.rb, test/remote/gateways/remote_epsilon_gmo_id_test.rb, test/remote/gateways/remote_epsilon_link_payment_test.rb, test/remote/gateways/remote_epsilon_test.rb, test/remote/gateways/remote_epsilon_virtual_account_test.rb, test/test_helper.rb, test/unit/billing/convenience_store_test.rb, test/unit/gateways/epsilon_test.rb
The MiniTest module is no longer working because the compatibility layer was removed in version 5.10, so I fixed it. I also corrected some tests that were failing due to hardcoding.
https://github.com/minitest/minitest/blob/master/History.rdoc#label-5.10.0+-2F+2016-11-30
And, increased the supported Ruby versions to include the latest stable releases.
=> Update to Minitest 5.10+ and Upgrade Supported Ruby Versions

README.md
Looking at the code, the correct argument name is `three_d_secure_pa_res`, not `three_d_secure_pares`.
https://github.com/pepabo/active_merchant-epsilon/blob/e601e165c6b510f362ab686233098deee11a3039/lib/active_merchant/billing/gateways/epsilon.rb#L161
=> Fix argument name in README
